function safeNextPath(value){
  if(!value||typeof value!=='string'||value.includes('\\')||value.startsWith('//')||/^[a-z][a-z0-9+.-]*:/i.test(value))return null;
  try{const target=new URL(value,location.href);if(target.origin!==location.origin)return null;if(!/\.html$/i.test(target.pathname))return null;return `${target.pathname}${target.search}${target.hash}`}catch{return null}
}
async function hashPassword(value){try{const data=new TextEncoder().encode(value),buf=await crypto.subtle.digest('SHA-256',data);return [...new Uint8Array(buf)].map(b=>b.toString(16).padStart(2,'0')).join('')}catch{let h=2166136261;for(let i=0;i<value.length;i++)h=Math.imul(h^value.charCodeAt(i),16777619);return(h>>>0).toString(16)}}
async function signupUser({name,email,password}){email=email.trim().toLowerCase();const users=Store.read(KEYS.users);if(users.some(u=>u.email===email))throw new Error('An account with this email already exists.');if(password.length<8||!/[A-Z]/.test(password)||!/[a-z]/.test(password)||!/[0-9]/.test(password))throw new Error('Use 8+ characters with upper, lower, and a number.');const user={id:uid('U'),name:name.trim(),email,passwordHash:await hashPassword(password),role:'user',blocked:false,createdAt:nowISO()};Store.write(KEYS.users,[...users,user]);return user}
async function loginUser(email,password,role='user',remember=true){email=email.trim().toLowerCase();const users=Store.read(KEYS.users);const u=users.find(x=>x.email===email);if(!u||u.role!==role)throw new Error('Account not found.');if(u.blocked)throw new Error('This account is blocked by an administrator.');if((await hashPassword(password))!==u.passwordHash)throw new Error('Incorrect password.');return setSession(u,remember)}
function setSession(user,remember=true){const session={id:user.id,name:user.name,email:user.email,role:user.role,at:nowISO()};Store.remove(KEYS.session);sessionStorage.removeItem(KEYS.session);if(remember)Store.write(KEYS.session,session);else sessionStorage.setItem(KEYS.session,JSON.stringify(session));return session}
function getSession(){try{const local=localStorage.getItem(KEYS.session);if(local)return JSON.parse(local)}catch{}try{const session=sessionStorage.getItem(KEYS.session);if(session)return JSON.parse(session)}catch{}return null}
function logout(){Store.remove(KEYS.session);sessionStorage.removeItem(KEYS.session);location.href='../index.html'}
